### ISSUE TITLE
Issue setting tags

### ISSUE THREAD

**Issue by ilyauts** [Azure/azure-keyvault-java#7]
```
keyVaultClient.setSecret(new SetSecretRequest.Builder(vault, Utils.getKeyName(id, keyDTO.getContentType()), keyDTO.getValue())
                .withTags(keyDTO.getTags())
                .withContentType(keyDTO.getContentType())
                .build()); 
```

Results in the following error:

```
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isSupertypeOf(Ljava/lang/reflect/Type;)Z

	at com.microsoft.rest.Validator.validate(Validator.java:51)
	at com.microsoft.azure.keyvault.KeyVaultClientImpl.setSecretWithServiceResponseAsync(KeyVaultClientImpl.java:2564)
	at com.microsoft.azure.keyvault.KeyVaultClientImpl.setSecret(KeyVaultClientImpl.java:2501)
	at com.microsoft.azure.keyvault.KeyVaultClient.setSecret(KeyVaultClient.java:741)
	at com.roardata.service.impl.CompetitionSourceServiceImpl.storeApiKey(CompetitionSourceServiceImpl.java:92)
```

For completeness, id is a Long and keyDTO is an object of the following class:

```
public class KeyDTO {

    private String value;
    private String contentType;
    private Map<String, String> tags;

    ...etc
}
```

Everything works in the absence of .withTags(), but we need tags for each key in our application. According to some preliminary research, it seems like it could be an Azure dependency to an outdated version of guava (18 instead of 19) as per: 

https://groups.google.com/forum/#!searchin/google-appengine/java.lang.NoSuchMethodError$3A$20com.google.common.reflect.TypeToken.isSupertypeOf(Ljava$2Flang$2Freflect$2FType$3B)Z%7Csort:relevance/google-appengine/QkH-Y8ZRV6M/We8k4IoYAAAJ

Note: I'm getting this for version 1.0.0 from the maven repo

Please advise

**Comment by ilyauts** [comment]
Resolved, ignore.
